name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip pipenv
        pipenv install --dev

    - name: Run tests
      run: bin/check

    - name: Upload coverage report
      run: pipenv run coveralls
      env:
        COVERALLS_REPO_TOKEN:  ${{ secrets.COVERALLS_REPO_TOKEN }}
